# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0E0E12"
foreground = "#E9E0CC"

[colors.normal]
black   = "#39393D"
red     = "#A4396B"
green   = "#9F387A"
yellow  = "#A0603C"
blue    = "#B2523D"
magenta = "#A97332"
cyan    = "#BF9737"
white   = "#D7CAAE"

[colors.bright]
black   = "#968E7A"
red     = "#A4396B"
green   = "#9F387A"
yellow  = "#A0603C"
blue    = "#B2523D"
magenta = "#A97332"
cyan    = "#BF9737"
white   = "#D7CAAE"
