# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#140F0F"
foreground = "#FFF5EE"

[colors.normal]
black   = "#3E3A3A"
red     = "#D33227"
green   = "#E84F12"
yellow  = "#E46E28"
blue    = "#F5A45E"
magenta = "#ECDD4B"
cyan    = "#FFA867"
white   = "#F6E9DE"

[colors.bright]
black   = "#ADA39B"
red     = "#D33227"
green   = "#E84F12"
yellow  = "#E46E28"
blue    = "#F5A45E"
magenta = "#ECDD4B"
cyan    = "#FFA867"
white   = "#F6E9DE"
