[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true
linemode = "size"
show_hidden = true
show_symlink = true

[preview]
wrap = "no"
tab_size = 2
image_filer = "lanczos3"
image_quality = 90
# ueberzug_scale  = 1
# ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]
edit = [{ run = '$EDITOR "$@"', block = true, for = "unix" }]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
