# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0F1215"
foreground = "#F7EBEE"

[colors.normal]
black   = "#373A3D"
red     = "#3E81BD"
green   = "#2CBBA0"
yellow  = "#A252C1"
blue    = "#4D8FC9"
magenta = "#A557C8"
cyan    = "#E86289"
white   = "#EBDADE"

[colors.bright]
black   = "#A4989C"
red     = "#3E81BD"
green   = "#2CBBA0"
yellow  = "#A252C1"
blue    = "#4D8FC9"
magenta = "#A557C8"
cyan    = "#E86289"
white   = "#EBDADE"
